### ISSUE TITLE
401 Unauthorized

### ISSUE THREAD

**Issue by dirkmoors** [jadahl/mod_restful#20]
Unfortunatly, I run into the same as stated here: https://github.com/jadahl/mod_restful/issues/11, which is already closed. 

 I've created a gist with my ejabberd.yml, the console output and the request I make, which results in an 401 Unauthorized error:
https://gist.github.com/dirkmoors/4b60c9573d3d49cbf1cd

My modules section in ejabberd.yml looks like:

```
modules:
  mod_restful:
    api:
      - path: ["admin"]
        module: mod_restful_admin
        params:
          key: "secret"
          allowed_commands: [register, unregister]
      - path: ["register"]
        module: mod_restful_register
        params:
          key: "secret"
  ...
```

As you can see in the console output, there are no issues loading the module itself.
Obviously, the user I use in the example; "admin@service.vrijhof.com" is an existing user.

I've compiled ejabberd Community (13.12) from source on Ubuntu 14.04 LTS, and I've used the master branch of mod_restful. What could be wrong here?
